# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lJuuwR1PVY8QbIJbLqegjYze_7Bun2Zz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Social_Network_Ads.csv')

df.head()

df.info()

df.isnull().sum()

df.duplicated().sum()

df.describe()

df.iloc[:,2:]

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(df.drop(['Purchased','Gender'], axis=1), df['Purchased'], test_size=0.2, random_state=0)

x_train

y_train

x_train.shape

x_test.shape

from sklearn.preprocessing import StandardScaler

scale = StandardScaler()

x_train_scaled = scale.fit_transform(x_train)

x_test_scaled = scale.transform(x_test)

x_train_scaled

x_test_scaled

# we need to convert them to data frame form numpy
x_train_scaled = pd.DataFrame(x_train_scaled, columns= x_train.columns)

x_train_scaled

x_test_scaled = pd.DataFrame(x_test_scaled, columns= x_test.columns)

x_test_scaled

# now lets test this data on the model
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()

LR_Scaled = LogisticRegression()

y_pred = LR.fit(x_train, y_train).predict(x_test)

y_pred_scaled = LR_Scaled.fit(x_train_scaled, y_train).predict(x_test_scaled)

from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

accuracy_score(y_test, y_pred_scaled)