# -*- coding: utf-8 -*-
"""Scikit-Learn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgSbUbFjpV3nGk0lD1bSgoIGda53Rw70
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install scikit-learn

# from sklearn.datasets import fetch_california_housing

# X,y=fetch_california_housing(return_X_y=True)

"""**Loading the Model.......**"""

# from sklearn.neighbors import KNeighborsRegressor

#for creation lets take a varible that points to the model
# model = KNeighborsRegressor()

#hey model fit your self with the data i have
# model.fit(X,y)

#hey model now can you predict y uisng x
# model.predict(X)
#number of predictions we are making is equal to the number of rows in the array

# we can also do it like this when we say
# from sklearn.linear_model import LinearRegression

# we agagin take a varibale to point at the model
# model2 = LinearRegression()

# then we will again say it to learn from the data we have
# model2.fit(X,y)

# then we will do the predictions
# model2.predict(X)

# we can also write these as
# from sklearn.neighbors import KNeighborsRegressor
# import matplotlib.pyplot as plt
# from sklearn.preprocessing import StandardScaler
# from sklearn.pipeline import Pipeline

# model = KNeighborsRegressor().fit(X,y)
# pipe = Pipeline([
#     ("scale", StandardScaler()),
#     ("model", KNeighborsRegressor())
# ])
# so this is how we create the pipeline

# pipe.fit(X,y)

# pred = pipe.predict(X)

#so y is the true values of array and pred is also the values of array
# so we will create a scatter plot using it
# plt.scatter(pred, y)

#now with the help of grid search cv we will so this again
from sklearn.datasets import fetch_california_housing
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

# now we will create the varibale and point it to the data and then create the pipeline

X,y = fetch_california_housing(return_X_y=True)

pipe = Pipeline([
    ("scale", StandardScaler()),
    ("model", KNeighborsRegressor(n_neighbors=1))

])
# pipe.get_params() to get the paramtere in the model to be used as grid

# so here will be our new model as we say
mod = GridSearchCV(estimator=pipe, param_grid={'model__n_neighbors': [1,2,3,4,5,6,7,8,9,10]}, cv = 3)

mod.fit(X,y);
import pandas as pd #just to make the cv results properly we can use pandas
pd.DataFrame(mod.cv_results_)











