# -*- coding: utf-8 -*-
"""Scikit_Data_preprocessing_Tools.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gRajGpyco64kC4wXVEo8uj2VdAZ2Tc7S
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("drawndata1.csv")

df.head(3)

X = df[['x', 'y']].values
y = df['z'] == "a"

plt.scatter(X[:, 0], X[:, 1], c=y)

"""**We are doing preprocessing**"""

from sklearn.preprocessing import StandardScaler, QuantileTransformer
X_new = QuantileTransformer().fit_transform(X)

plt.scatter(X_new[:, 0], X_new[:, 1], c=y)

"""**Another type of preprocessing is converting string to numeric data**"""

import numpy as np
arr = np.array(["low", "low", "high", "medium"]).reshape(-1, 1)
arr

from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(sparse_output=False)

enc.fit_transform(arr)
# if we will make the sparse true then it will convert them into a sparse matrix
# there fore in the model object change it to sparse = False