# -*- coding: utf-8 -*-
"""Vector_stroes_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rF7SQCSp2QvXP2ddoYWCQyII4h72hZ1Q
"""

!pip install langchain langchain_groq langchain-community chromadb tiktoken langchain-huggingface

# we will create documents
from langchain_core.documents import Document

doc1 = Document(
        page_content="""
        Ashutosh is a professional badminton player.
        He practices daily and participates in national tournaments.
        His strengths are agility, speed, and quick reflexes.
        """,
        metadata={
            "player_name": "Ashutosh",
            "sport": "Badminton",
            "experience": "Professional",
            "country": "India"
        }
    )
doc2 = Document(
        page_content="""
        Paritosh is a football player who plays as a striker.
        He has excellent ball control and scoring abilities.
        He regularly trains with his football club.
        """,
        metadata={
            "player_name": "Paritosh",
            "sport": "Football",
            "position": "Striker",
            "country": "India"
        }
    )
doc3 = Document(
        page_content="""
        Nachos is a competitive food challenge participant.
        He is famous for participating in spicy chicken eating contests.
        He has won multiple local food competition events.
        """,
        metadata={
            "player_name": "Nachos",
            "category": "Food Competition",
            "speciality": "Chicken Challenges",
            "country": "India"
        }
    )
doc4 =   Document(
        page_content="""
        Gautom is a chef and chicken recipe expert.
        He specializes in grilled chicken dishes and culinary experiments.
        He also teaches cooking workshops.
        """,
        metadata={
            "player_name": "Gautom",
            "profession": "Chef",
            "speciality": "Chicken Recipes",
            "country": "India"
        }
    )
doc5 =  Document(
        page_content="""
        Semona is an international badminton player.
        She focuses on doubles matches and advanced racket techniques.
        She has represented her academy in multiple championships.
        """,
        metadata={
            "player_name": "Semona",
            "sport": "Badminton",
            "match_type": "Doubles",
            "country": "India"
        }
    )

# now i will create the list of doc
docs = [doc1, doc2, doc3, doc4, doc5]

# now creating the embedding vector
from langchain_huggingface import HuggingFaceEmbeddings
embedding_model = HuggingFaceEmbeddings(model = 'sentence-transformers/all-MiniLM-L6-v2')

# now we will create our vector
from langchain_community.vectorstores import Chroma
vector_store = Chroma(
    embedding_function = embedding_model,
    persist_directory = 'my_chroma_db',
    collection_name = 'sample'
)

# now adding our docs
vector_store.add_documents(docs)

# now we will print values from out db
vector_store.get(include =['embeddings','metadatas', 'documents'])

# now we will perform the similarty search
vector_store.similarity_search(query="Who is Ashutosh", k=2)

# using the filters
# vector_store.similarity_search_with_score(query="badminton", k=2)
vector_store.similarity_search_with_score(query="", filter={'sport':'Badminton'})

